services:
  xnz-pt-automation:
    image: qqxnz/xnz-pt-automation:0.5.0
    container_name: xnz-pt-automation
    restart: always
    ports:
      - "3180:3180"
    environment:
      PORT: "3180"
      DATA_DIR: /data
      DEFAULT_ADMIN_PASSWORD: "123456"
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data
